[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "node src/index.js"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "ON_FAILURE"
numReplicas = 1

[service]
name = "bots-app"

