[build]
builder = "NIXPACKS"
buildCommand = "npm install"

[deploy]
startCommand = "npm start"
restartPolicy = "ON_FAILURE"
healthcheckPath = "/"
healthcheckTimeout = 100

[service]
name = "discord-bot"

